### ISSUE TITLE
Voronoi creation doesn't work with degree coordinates

### ISSUE THREAD

**Issue by vvirkki** [mkkallio/hydroc2s#1] opened 2018-07-31 12:48 UTC
Traceback of Voronoi weighting with coordinates in degrees:

```
Error in CPL_geos_voronoi(x, st_sfc(envelope), dTolerance = dTolerance,  : 
  Evaluation error: TopologyException: Input geom 1 is invalid: Self-intersection at or near point 105.5125000008 15.5708336588 at 105.5125000008 15.5708336588. 
18.
stop(structure(list(message = "Evaluation error: TopologyException: Input geom 1 is invalid: Self-intersection at or near point 105.5125000008 15.5708336588 at 105.5125000008 15.5708336588.", 
    call = CPL_geos_voronoi(x, st_sfc(envelope), dTolerance = dTolerance, 
        bOnlyEdges = bOnlyEdges), cppstack = NULL), class = c("Rcpp::eval_error", 
"C++Error", "error", "condition"))) 
17.
CPL_geos_voronoi(x, st_sfc(envelope), dTolerance = dTolerance, 
    bOnlyEdges = bOnlyEdges) 
16.
st_sfc(CPL_geos_voronoi(x, st_sfc(envelope), dTolerance = dTolerance, 
    bOnlyEdges = bOnlyEdges)) 
15.
st_voronoi.sfc(sf::st_union(vorPoints), bbox, dTolerance = 0.1) 
14.
sf::st_voronoi(sf::st_union(vorPoints), bbox, dTolerance = 0.1) 
13.
eval(lhs, parent, parent) 
12.
eval(lhs, parent, parent) 
11.
sf::st_voronoi(sf::st_union(vorPoints), bbox, dTolerance = 0.1) %>% 
    sf::st_cast() %>% sf::st_cast("POLYGON") %>% sf::st_sf() %>% 
    sf::st_join(vorPoints) %>% lwgeom::st_make_valid() %>% dplyr::group_by_(riverID) %>% 
    dplyr::summarise() %>% sf::st_intersection(sf::st_geometry(aoi)) 
10.
withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning")) 
9.
suppressWarnings(sf::st_voronoi(sf::st_union(vorPoints), bbox, 
    dTolerance = 0.1) %>% sf::st_cast() %>% sf::st_cast("POLYGON") %>% 
    sf::st_sf() %>% sf::st_join(vorPoints) %>% lwgeom::st_make_valid() %>% 
    dplyr::group_by_(riverID) %>% dplyr::summarise() %>% sf::st_intersection(sf::st_geometry(aoi))) 
8.
withCallingHandlers(expr, message = function(c) invokeRestart("muffleMessage")) 
7.
suppressMessages(suppressWarnings(sf::st_voronoi(sf::st_union(vorPoints), 
    bbox, dTolerance = 0.1) %>% sf::st_cast() %>% sf::st_cast("POLYGON") %>% 
    sf::st_sf() %>% sf::st_join(vorPoints) %>% lwgeom::st_make_valid() %>% 
    dplyr::group_by_(riverID) %>% dplyr::summarise() %>% sf::st_intersection(sf::st_geometry(aoi)))) at C:\Users\Vili\AppData\Local\Temp\RtmpiAXEnH\file1e587c4c7dfc#20
6.
river_voronoi(river, aoi, verbose = verbose) 
5.
compute_weights(rivers, grid, "area", aoi = st_sf(bbox), riverID = "SegmentID", 
    verbose = show_hs_output) at ucscript.R#102
4.
eval(ei, envir) 
3.
eval(ei, envir) 
2.
withVisible(eval(ei, envir)) 
1.
source("C:/Users/Vili/hydrostreamer/uncertainty/ucscript.R") 
```

**Comment by mkkallio** [comment] 2018-08-07 18:41
Hi, thanks for posting this issue.
I could reproduce this with the example data you provide (elsewhere). It appears to be an issue with the edges, when area of interest is set equal to the bounding box of the river network.

The issue disappeared when a subset of river segments were selected.

I could not find why the self-intersection occurs, since there were no overlapping points for voronoi (but perhaps points and bounding box intersection causes this?

Closing since as far as I understand, this is not an issue with the function itself, but of input data.

**Closed as completed by mkkallio** 2018-08-07 18:41 UTC
